baseURL = "https://traderhs.github.io/"
languageCode = "ko-kr"
title = "Traderhs Blog"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
