baseURL = "https://traderhs.github.io/"
languageCode = "ko-kr"
title = "QuantBoard"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^VISITOR_API_URL$']

[params]
  defaultTheme = "auto"
  env = "production"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true

  [params.homeInfoParams]
    Title = "QuantBoard"
    Content = "퀀트 트레이더를 꿈꾸고 있습니다."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/traderhs"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:example@gmail.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
